"""remove schedules and schedule_entries

Revision ID: e9e67aed10f0
Revises: 24611aa100f8
Create Date: 2026-04-09 12:01:31.373501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9e67aed10f0'
down_revision: Union[str, Sequence[str], None] = '24611aa100f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_entries_id'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'RUNNING', 'DONE', 'FAILED'), nullable=False),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('schedules_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lecturer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_slot_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('schedule_entries_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], name=op.f('schedule_entries_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('schedule_entries_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('schedule_entries_ibfk_4'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], name=op.f('schedule_entries_ibfk_5'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_schedule_entries_id'), 'schedule_entries', ['id'], unique=False)
    # ### end Alembic commands ###
